# Generated by Django 3.0.7 on 2020-08-02 17:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'demande_consultation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(null=True)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=1)),
                ('telephone', models.CharField(max_length=200, null=True)),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('date_naissance', models.DateField(null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('mod_date_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medecin',
                'managed': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=30, null=True)),
                ('telephone', models.CharField(max_length=30, null=True)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=1)),
            ],
            options={
                'db_table': 'personne',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('icon', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'specialite',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StructureSanitaire',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('denomination', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=150)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('mod_date_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'structure_sanitaire',
                'managed': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.IntegerField()),
                ('demande_consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation.DemandeConsultation')),
            ],
            options={
                'db_table': 'notification',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedecinStructureSanitaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_demande', models.BooleanField(default=False)),
                ('demandeur', models.CharField(choices=[('M', 'Medecin'), ('S', 'StructureSanitaire')], max_length=1)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('mod_date_time', models.DateTimeField(auto_now=True)),
                ('centre_medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecin_structure_sanitaires', to='consultation.StructureSanitaire')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='medecin_structure_sanitaires', to='consultation.Medecin')),
            ],
            options={
                'db_table': 'medecin_structure_sanitaire',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='medecin',
            name='specialite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultation.Specialite'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='structure_sanitaires',
            field=models.ManyToManyField(related_name='medecins', through='consultation.MedecinStructureSanitaire', to='consultation.StructureSanitaire'),
        ),
        migrations.CreateModel(
            name='EmploiDuTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaire_start', models.TimeField()),
                ('horaire_end', models.TimeField()),
                ('jour', models.DateField()),
                ('medecin_structure_sanitaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultation.MedecinStructureSanitaire')),
            ],
            options={
                'db_table': 'emploi_du_temp',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='demandeconsultation',
            name='medecin_centre_medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultation.MedecinStructureSanitaire'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=150)),
                ('interrogatoire', models.CharField(max_length=150)),
                ('resume', models.CharField(max_length=150)),
                ('hypothese_diagnostique', models.CharField(max_length=150)),
                ('demande_consultation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultation.DemandeConsultation')),
            ],
            options={
                'db_table': 'consultation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='consultation.Personne')),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('mod_date_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultation.Medecin')),
            ],
            options={
                'db_table': 'patient',
                'managed': True,
            },
            bases=('consultation.personne',),
        ),
        migrations.AddField(
            model_name='demandeconsultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultation.Patient'),
        ),
    ]
