# Generated by Django 3.0.7 on 2020-07-11 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='personne',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='username',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='create_date_time',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mod_date_time',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='personne',
        ),
        migrations.AddField(
            model_name='medecin',
            name='authuser_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='consultation.AuthUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='personne_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='consultation.Personne'),
            preserve_default=False,
        ),
    ]
