# Generated by Django 3.0.7 on 2020-08-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='hypothese_diagnostique',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='interrogatoire',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='motif',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='resume',
            field=models.TextField(),
        ),
    ]
