# Generated by Django 3.0.7 on 2020-08-06 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structuresanitaire',
            options={'managed': True, 'ordering': ['denomination']},
        ),
        migrations.AddField(
            model_name='structuresanitaire',
            name='owner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
