# Generated by Django 3.0.7 on 2020-07-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='create_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='mod_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
