# Generated by Django 3.0.7 on 2020-08-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_auto_20200806_1341'),
        ('consultation', '0002_auto_20200807_0838'),
    ]

    operations = [
    ]
