# Generated by Django 3.0.7 on 2020-07-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_auto_20200722_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecinstructuresanitaire',
            name='create_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medecinstructuresanitaire',
            name='mod_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='create_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='mod_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='structuresanitaire',
            name='create_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='structuresanitaire',
            name='mod_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
