# Generated by Django 3.0.7 on 2020-08-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_patient_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuresanitaire',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
