# Generated by Django 3.0.7 on 2020-07-22 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_auto_20200722_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='date_naissance',
            field=models.DateField(default=datetime.date(2020, 7, 22)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personne',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='personne',
            name='telephone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='adresse',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
