# Generated by Django 3.0.7 on 2020-08-07 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_structuresanitaire_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temprature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pression_arterielle', models.DecimalField(decimal_places=2, max_digits=5)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taille', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'db_table': 'constantes',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='structure_sanitaire',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='consultation.StructureSanitaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='groupage',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='habitude_alimentaires',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='maladies',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
