# Generated by Django 3.0.7 on 2020-08-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_auto_20200807_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='created_by',
            new_name='doctor',
        ),
    ]
