# Generated by Django 3.0.7 on 2020-07-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_auto_20200722_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='adresse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
