# Generated by Django 3.0.7 on 2020-08-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_auto_20200807_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='structure_sanitaire',
        ),
    ]
