# Generated by Django 3.0.7 on 2020-08-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_remove_consultation_structure_sanitaire'),
        ('consultation', '0004_merge_20200807_1131'),
    ]

    operations = [
    ]
