# Generated by Django 3.0.7 on 2020-08-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_merge_20200808_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='groupage',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
