# Generated by Django 3.0.7 on 2020-07-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0010_medecin_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialite',
            name='img_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
