# Generated by Django 3.0.7 on 2020-08-15 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0011_patient_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeconsultation',
            name='medecin_centre_medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.MedecinStructureSanitaire'),
        ),
        migrations.AlterField(
            model_name='emploidutemp',
            name='medecin_structure_sanitaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.MedecinStructureSanitaire'),
        ),
    ]
