# Generated by Django 3.0.7 on 2020-07-30 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0011_specialite_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialite',
            old_name='img_url',
            new_name='icon',
        ),
    ]
