# Generated by Django 3.0.7 on 2020-08-18 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0012_auto_20200815_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constantes',
            name='pression_arterielle',
        ),
        migrations.AddField(
            model_name='constantes',
            name='cholesterol',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constantes',
            name='diastolique',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constantes',
            name='glycemie',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constantes',
            name='pouls',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constantes',
            name='systolique',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='constantes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultation.Constantes'),
        ),
    ]
