# Generated by Django 3.0.7 on 2020-07-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0012_auto_20200730_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='structure_sanitaires',
            field=models.ManyToManyField(related_name='medecins', through='consultation.MedecinStructureSanitaire', to='consultation.StructureSanitaire'),
        ),
    ]
