# Generated by Django 3.0.7 on 2020-07-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0013_medecin_structure_sanitaires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecinstructuresanitaire',
            name='date_affiliation',
        ),
        migrations.AddField(
            model_name='medecinstructuresanitaire',
            name='demandeur',
            field=models.CharField(choices=[('M', 'Medecin'), ('S', 'StructureSanitaire')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medecinstructuresanitaire',
            name='status_demande',
            field=models.BooleanField(default=False),
        ),
    ]
