# Generated by Django 3.0.7 on 2020-08-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0013_auto_20200818_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constantes',
            old_name='temprature',
            new_name='temperature',
        ),
    ]
