# Generated by Django 3.0.7 on 2020-08-19 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0015_auto_20200819_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='constantes',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='consultation.Constantes'),
            preserve_default=False,
        ),
    ]
