# Generated by Django 3.0.7 on 2020-08-25 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0016_auto_20200819_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeconsultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='demande_consultations', to='consultation.Patient'),
        ),
    ]
