# Generated by Django 3.0.7 on 2020-08-26 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0017_auto_20200825_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='demande_consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultation', to='consultation.DemandeConsultation'),
        ),
        migrations.AlterField(
            model_name='demandeconsultation',
            name='date_consultation',
            field=models.DateField(),
        ),
    ]
