# Generated by Django 3.0.7 on 2020-08-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0018_auto_20200826_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeconsultation',
            name='date_consultation',
            field=models.DateTimeField(),
        ),
    ]
