# Generated by Django 3.0.7 on 2020-09-02 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0020_auto_20200902_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='ordonnance',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='consultation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordonnances', to='consultation.Consultation'),
            preserve_default=False,
        ),
    ]
