# Generated by Django 3.0.7 on 2020-09-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0021_auto_20200902_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordonnance',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='produit',
            name='forme',
            field=models.CharField(choices=[('CP', 'Comprimé'), ('SusB', 'Suspension Buvable'), ('SolB', 'Solution Buvable'), ('Sirop', 'Sirop'), ('Inj', 'Injection'), ('Inh', 'Inhalation'), ('Spray', 'Spray'), ('Sachet', 'Sachet'), ('Pommade', 'Pommade'), ('Perlingual', 'Perlingual'), ('Gouttes', 'Gouttes'), ('SolInjBuv', 'Solution injectable et buvable'), ('Creme', 'Crème'), ('Perfusion', 'Perfusion'), ('Liquide', 'Liquide'), ('Poudre', 'Poudre'), ('Supp', 'Suppositoire'), ('PomOph', 'Pommade ophtalmique'), ('Collyre', 'Collyre'), ('Caps', 'Capsules'), ('SolPerf', 'Soluté perfusable'), ('Gelule', 'Gélule'), ('GouttesAuric', 'Gouttes auriculaires')], default='Cp', max_length=20, null=True),
        ),
    ]
