# Generated by Django 3.0.7 on 2020-09-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0022_auto_20200904_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='quantité',
            new_name='quantite',
        ),
    ]
